#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : suitable
Version  : 0.17.2
Release  : 6
URL      : https://files.pythonhosted.org/packages/0c/c5/139eb5686f297c03b38fc5ad6d817f140daca8990062524640aa8b9672a0/suitable-0.17.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/0c/c5/139eb5686f297c03b38fc5ad6d817f140daca8990062524640aa8b9672a0/suitable-0.17.2.tar.gz
Summary  : Suitable is a thin wrapper around the Ansible API.
Group    : Development/Tools
License  : GPL-3.0
Requires: suitable-license = %{version}-%{release}
Requires: suitable-python = %{version}-%{release}
Requires: suitable-python3 = %{version}-%{release}
Requires: ansible
Requires: paramiko
BuildRequires : ansible
BuildRequires : buildreq-distutils3
BuildRequires : paramiko

%description
.. image:: https://cdn.jsdelivr.net/gh/seantis/suitable@master/docs/source/_static/logo.svg
:alt: Suitable
:width: 50%
:align: center

%package license
Summary: license components for the suitable package.
Group: Default

%description license
license components for the suitable package.


%package python
Summary: python components for the suitable package.
Group: Default
Requires: suitable-python3 = %{version}-%{release}

%description python
python components for the suitable package.


%package python3
Summary: python3 components for the suitable package.
Group: Default
Requires: python3-core
Provides: pypi(suitable)
Requires: pypi(ansible)

%description python3
python3 components for the suitable package.


%prep
%setup -q -n suitable-0.17.2
cd %{_builddir}/suitable-0.17.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1599847870
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/suitable
cp %{_builddir}/suitable-0.17.2/LICENSE %{buildroot}/usr/share/package-licenses/suitable/338650eb7a42dd9bc1f1c6961420f2633b24932d
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/suitable/338650eb7a42dd9bc1f1c6961420f2633b24932d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
